name: Build, Lint

on:
  push:
    branches: [ main, v1 ]
  pull_request:
    branches: [ main, v1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Build
        run: go build  ./...
